#!/usr/bin/env bash

# Load config file with API secrets
source config.sh

# Load the mailterlite bash library.
source lib/main.sh

## Account endpoint
# @cite https://developers.mailerlite.com/reference#account
mlite_get_account="${mlite_api_uri}me";

## Get account details
curl $mlite_get_account \
  -H "X-MailerLite-ApiKey: ${mlite_api_key}";
